server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;
    include /etc/nginx/mime.types;

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff2?)$ {
        try_files $uri =404;
        access_log off;
    }

    location / {
        limit_except GET HEAD POST {
            deny all;
        }
        try_files $uri $uri/ /index.html;
    }

    error_page 500 502 503 504 /50x.html;
}